### PR TITLE
@W-9021650 implement rev 2 of imperative extension

### PR DESCRIPTION
**Pull request by olivier-martin-sf**
When applied this patch updates the current implementation of imperative extension to the revision 2 specified in the [RFC](https://github.com/salesforce/utam-rfcs/pull/35).

More specifically, it:

- prevent use of`external` method.
- deserialized imperative extension JSON objects in `UtamUtilityMethodAction` objects.
- add validations to prevent PO authors to write mixed compose statements.
- generate proper sub types of `Operand` and `Operation` for imperative extensions (`getComposeAction` method)
- generate the appropriate code statement.
- clean and delete all references to the previous implementation.
- add unit tests for the new implementation.

### CODE REVIEW

**Review by jimevanssfdc — CHANGES_REQUESTED** [review]
LGTM. I'm going to hold off merging until I get the build pipeline fixed. In the meantime, please merge current `dev` branch's `HEAD` revision and into this branch and resolve the conflicts.

**Comment by olivier-martin-sf** [comment]
Thank you Jim! I merged current `dev` branch and pushed the updated version of the branch. Feel free to merge it when it's appropriate

**Comment by olivier-martin-sf** [comment]
@jimevanssfdc I pushed a new commit that adds support for the `UtamUtilitiesContext` object, feel free to have a look when you have time

**Review by jimevanssfdc — APPROVED** [review]
LGTM

**Pull request merged**
